workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 15.4
    scripts:
      - name: Installeer Flutter dependencies
        script: |
          flutter pub get
      - name: Installeer CocoaPods
        script: |
          cd ios
          pod install
      - name: Bouw iOS app in Release modus
        script: |
          flutter build ios --release --no-codesign
      - name: Archiveer de iOS app en maak een .ipa bestand
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath build/Runner.xcarchive

          # Exporteren van het .ipa bestand
          xcodebuild -exportArchive \
          -archivePath build/Runner.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath ios/build
    artifacts:
      - ios/build/*.ipa  # Het pad naar je .ipa bestand
