name: Flutter Web CI

on:
  push:
    branches:
      - main  # of de branch waar je je wijzigingen push't

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v4
      with:
        channel: 'stable'

    - name: Enable web
      run: flutter config --enable-web

    - name: Get dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web --web-renderer html --base-href "/team_maker2/"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        cname: vonfoxie87.github.io  # Optioneel, als je een eigen domein hebt ingesteld